# Generated by Django 3.0.7 on 2020-07-07 12:06
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='from_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='to_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guess',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.Game'),
        ),
    ]
