# Generated by Django 3.0.7 on 2020-07-12 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_auto_20200707_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guess_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
